services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adtime-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgres://postgres:password@db:5432/adtime
    depends_on:
      - db
    restart: always
    networks:
      - pompon-network

  db:
    image: postgres:15
    container_name: adtime-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adtime
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - adtime-network

volumes:
  postgres_data:

networks:
  adtime-network:
    driver: bridge
